# 1. 튜플
여러 가지 데이터 타입의 값을 저장할 수 있는, 변경 불가능(immutable)한 순서가 있는 컬렉션입니다.

In [ ]:
tu1 = (1,) #데이터 한개만 넣을때는 1, 라고 입력을 한다.
# 만약 그냥 1을 넣으면 tulple로 만들어지지 않고, 데이터 1로 지정이 된다. 그래서 고정값을 지정하기 위해 1, 로 넣는다.
print (tu1)

# tu1[0] = 100 # 'tuple' object does not support item assignment <- 한마디로 tuple은 수정이 불가능하다.

(1,)

In [ ]:
tu2 = (1, 3, 5, 7)
print (tu2)

(1, 3, 5, 7)

In [ ]:
tu3 = 1, 3, 5, 7 #()를 지정안해도 tuple로 저장이 된다.
print(tu3)
print(type(tu3))

(1, 3, 5, 7)
<class 'tuple'>

In [ ]:
tu4 = ('apple', 'banana', ('🍏', '🍑'))
print(tu4)
print(tu4[0]) # 인덱스 0번의 값을 출력
print(tu4[2][0]) # 인덱스 2번의 값중에 1번째
print(type(tu4))
print(type(tu4[2])) # <class 'tuple'>
print(type(tu4[2][0])) # 사과의 타입은 string, 이유는 ()로 넣었기 때문에 string문자열로 저장이 된다.

('apple', 'banana', ('🍏', '🍑'))
apple
🍏
<class 'tuple'>
<class 'tuple'>
<class 'str'>

In [ ]:
tu5 = ('apple', 'banana', ['🍏', '🍑'])
print(tu5)
print(tu5[2][0])
print(type(tu5)) # tuple
print(type(tu5[2])) # list
print(type(tu5[2][0])) # str

# tu5[0] = 'orange' #'tuple' object does not support item assignment, tuple이여서 에러발생
# tu5[2] = '🥓' # 'tuple' object does not support item assignment, list자체는 tuple것이여서 에러발생
tu5[2][0] = '🥓' # 이렇게 list에 정확하게 지정을 하면 수정이 가능하다.
print (tu5)

('apple', 'banana', ['🍏', '🍑'])
🍏
<class 'tuple'>
<class 'list'>
<class 'str'>
('apple', 'banana', ['🥓', '🍑'])

In [ ]:
# 인덱싱 : 튜플의 각 항목은 위치(인덱스)를 가지고 있으며, 인덱스를 사용하여 접근할 수 있습니다. 인덱스는 0부터 시작합니다.
tu1 = (1, 2, 'apple', 'banana')
print(tu1[0]) # 인덱스 0번의 값을 출력
print(tu1[-1]) # 인덱스 끝자리를 출력

1
banana

In [ ]:
# 슬라이싱 : 튜플의 일부분만을 추출할 수 있습니다.
tu1 = (1, 2, 'apple', 'banana')
print(tu1[1:]) # 인덱스 1번부터 끝까지 출력
print(tu1[1:3]) # 인덱스 1번부터 3번전까지 출력

(2, 'apple', 'banana')
(2, 'apple')

In [ ]:
# 연산 : 튜플 간의 + 연산으로 리스트를 결합할 수 있고, * 연산으로 리스트를 반복할 수 있다.
tu1 = (10, 20, 30)
tu2 = (40, 50, 60)

print (tu1 + tu2)
print (tu2 + tu1)

tu1 = tu1 + (40, 50) # tuple은 변경이 불가능한데, 왜 + 연산자로 출력이 가능하냐? 라고 물으면 tuple속에 있는 데이터의 변경은 안되지만 뒤쪽에 추가만 하는것은 가능하다.
print(tu1)

print(tu1 * 3) # 3번 반복

(10, 20, 30, 40, 50, 60)
(40, 50, 60, 10, 20, 30)
(10, 20, 30, 40, 50)
(10, 20, 30, 40, 50, 10, 20, 30, 40, 50, 10, 20, 30, 40, 50)

In [ ]:
tu3 = (10, 20, 30)
print(tu3[0] + tu3[2]) # 10 + 30 = 40

40

In [ ]:
# 언패킹 : 튜플의 항목들은 변수들에 할당될 수 있습니다.(리스트도 가능)
apple, banana = ('김사과', '반하나') # 앞쪽 변수에 원하는 값을 지정하여 넣어서 사용할 수 있다.
print(apple)
print(banana)

김사과
반하나

In [ ]:
# 멤버십 테스트 : in 연산자를 사용하여 튜플에 특정 값이 있는지 확인할 수 있습니다. (리스트도 가능)
2 in (2, 4, 6, 8, 10) # 2라는 값이 ()안에 있는지 확인

True

In [ ]:
# 튜플의 정렬 : 튜플은 sort() 메서드를 제공하지 않습니다.sorted() 함수를 사용합니다.
# 이유는 : 데이터의 수정이 안되기 때문에 sort를 사용하면 안됩니다.
tu1 = (1, 3, 2, 0)
tu2 = sorted(tu1) # sorted()를 사용하여 정렬, sorted의 반환형은 리스트이다.
print (tu2)

[0, 1, 2, 3]

In [ ]:
# 변환 : 튜플을 리스트로, 리스트를 튜플로 변환할 수 있습니다.
tu1 = (1, 2, 3, 4)
print(type(tu1)) # tuple
li1 = list(tu1)  # tu1을 list로 li1으로 변환
print(type(li1)) # list
tu2 = tuple(li1) # li1을 tuple로 tu2로 변환
print(type(tu2)) # tuple
# tuple과 list의 타입의 변환은 간단하게 변경이 가능하다.
# 한마디로 "이 차는 이제 제것입니다. 제 명의로 등록이 된것입니다."라고 생각하면 편하다.

<class 'tuple'>
<class 'list'>
<class 'tuple'>

# 2. input함수
* 사용자(개발자)에게 데이터를 입력받을 수 있는 함수
* 데이터는 항상 문자형으로 입력받음

In [1]:
input()

KeyboardInterrupt: ignored

In [ ]:
name = input() # name의 변수에 input이라는 입력 변수를 선언
print (name) # input에서 받은 데이터 값을 name으로 출력하라

In [ ]:
name = input('이름을 출력하세요 : ')
print(f'{name}님 안녕하세요')

In [ ]:
name, age, weight = '김사과', 20, 50.5 # type은 tuple, 이렇게 넣는 방법을 언패킹이라고 한다.
print (name)
print (age)
print (weight)
# 데이터가 이렇게 잘 들어가게 된다.

In [ ]:
name, age, weight = input('이름, 나이, 몸무게를 차례대로 입력하세요 : ').split(' ')
print (name)
print (age + '살')
print (weight + 'kg')

In [ ]:
num1 = input('첫번째 숫자를 입력하세요 : ')
num2 = input('두번째 숫자를 입력하세요 : ')
print('결과 : ', num1 + num2) # 문자열이여서 해당 데이터끼리 붙는 현상이 발생

In [ ]:
# int() : 문자열을 숫자(정수)타입으로 변환
num1 = input('첫번째 숫자를 입력하세요 : ')
num2 = input('두번째 숫자를 입력하세요 : ')
print('결과 : ', int(num1) + int(num2)) # 형변환 int로 바꾼다음에 덧셈을 해라.

### 문제
* 국어점수, 영어점수, 수학점수를 한꺼번에 입력받아 총점, 평균을 구하는 프로그램을 작성해보자.
* 입력 방법
    * 100/80/95 (입력을 할때 / 로 입력을 받게 해라)

In [ ]:
korean, math, english = input('국어점수, 영어점수, 수학점수를 순서대로 입력하세요 : ').split('/')
total = int(korean) + int(math) + int(english)
avg = total / 3
print('총점 : ', total)
print('평균 : %.2f' %avg)
# 소숫점 2째 자리까지 할려고 하면 %.2f를 붙히면 된다.

### 과제
* 아래 코드를 설명하시오
* DM으로 보내는데 텍스트, 워드, ppt 형식으로 제출

In [ ]:
1.1 + 0.1 == 1.2

In [ ]:
1.1 + 0.1 > 1.2

위 처럼 1.1 + 0.1의 값이 1.2가 아닌이유
1.1 + 0.1 > 1.2보다 큰 이유를 서술하시오